-- 코드를 입력하세요
SELECT CART_ID
FROM CART_PRODUCTS L
INNER JOIN (
    SELECT *
    FROM CART_PRODUCTS
    WHERE NAME LIKE 'Milk'
) AS R USING (CART_ID)
WHERE L.NAME LIKE 'Yogurt'
GROUP BY CART_ID
ORDER BY CART_ID;