-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (SELECT FOOD_TYPE, MAX(FAVORITES) AS MX
      FROM REST_INFO
      GROUP BY FOOD_TYPE) L
INNER JOIN REST_INFO R USING (FOOD_TYPE)
WHERE R.FAVORITES = L.MX
ORDER BY FOOD_TYPE DESC;