-- 코드를 입력하세요
SELECT L.CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT L
INNER JOIN (SELECT CATEGORY, MAX(PRICE) AS MX
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    HAVING CATEGORY IN ('과자', '국', '김치', '식용유')) R
ON L.CATEGORY = R.CATEGORY
WHERE L.PRICE = R.MX
ORDER BY PRICE DESC;