-- 코드를 입력하세요
SELECT L.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR L
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY R USING (CAR_ID)
WHERE CAR_TYPE = '세단' AND START_DATE LIKE '2022-10%'
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;